food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>', views.detail, name='detail'),
]

food_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    item_name = models.CharField(max_length=100)
    item_desc = models.CharField(max_length=100)
    item_price = models.IntegerField()

food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Item

# Create your views here.
def index(request):
    items = Item.objects.all()
    context = {
        'items': items,
    }
    return render(request,'food/index.html', context)

    # template = loader.get_template('food/index.html')
    # return HttpResponse(template.render(context, request))


def detail(request, item_id):
    item = Item.objects.get(id=item_id)
    context = {
        'item': item
    }
    return render(request, 'food/detail.html', context)

food/templates/food/detail.html
{{ item.id }} -- {{ item.item_name }}

food/templates/food/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>
        <div class="navbar">
            <ul class="'nav-item"><a href="#" class=" nav-link">Add Item</a></ul>
            <!-- <a href="#" class="nav-item nav-link">Delete Item</a>
            <a href="#" class="nav-item nav-link">View Item</a> -->
        </div>
    </nav>


    {% for item in items %}
        <ul>
            <li>
                <a href="{% url 'food:detail' item.id %}">{{ item.id }} -- {{ item.item_name }}</a>
            </li>
        </ul>
    {% endfor %}
</body>
</html>